def create_timetable(input_json):
    # 1. DATA VALIDATION
    # 2. BUSINESS VALIDATION
    # 3. CONVERT AUTO MODE TO VALUES
    # 4. HARD CONSTRAINTS VALIDATION USING HEURITISC FIX
    # 5. IF SUCCESSFUL GENERERATE BEST TIMETABLE USING GENETIC ALGORITHM SATISYING SOFT CONSTRAINTS
    # 6. CREATE PDF


    